name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer apps
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ steps.get-date.outputs.date }}

    - name: Build with Buildozer
      uses: ArtemSuda/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: stable
    - name: Commit and Push APK to Repo
      run: |
        mkdir -p ready_apk
        cp bin/*.apk ready_apk/digma_recorder.apk
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add ready_apk/digma_recorder.apk
        git commit -m "Автосборка: Готовый APK обновлен"
        git push
        
